// Code generated by `codex-core/src/bin/hooks_rust_sdk.rs`. DO NOT EDIT.
//
// This module is generated from the Rust hook payload schema (source-of-truth).
//
// Re-generate from the repo:
//   cd codex-rs
//   cargo run -p codex-core --bin hooks_rust_sdk --features hooks-schema --quiet \
//     > hooks-sdk/src/generated.rs

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::BTreeMap;

pub type ExtraFields = BTreeMap<String, Value>;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HookPayload {
    #[serde(rename = "approval_id")]
    pub approval_id: Option<String>,
    #[serde(rename = "approval_policy")]
    pub approval_policy: Option<Value>,
    #[serde(rename = "attempt")]
    pub attempt: Option<u64>,
    #[serde(rename = "call_id")]
    pub call_id: Option<String>,
    #[serde(rename = "command")]
    pub command: Option<Vec<String>>,
    #[serde(rename = "cwd")]
    pub cwd: String,
    #[serde(rename = "duration_ms")]
    pub duration_ms: Option<u64>,
    #[serde(rename = "event_id")]
    pub event_id: String,
    #[serde(rename = "grant_root")]
    pub grant_root: Option<String>,
    #[serde(rename = "has_output_schema")]
    pub has_output_schema: Option<bool>,
    #[serde(rename = "hook_event_name")]
    pub hook_event_name: String,
    #[serde(rename = "input_item_count")]
    pub input_item_count: Option<u64>,
    #[serde(rename = "input_messages")]
    pub input_messages: Option<Vec<String>>,
    #[serde(rename = "kind")]
    pub kind: Option<String>,
    #[serde(rename = "last_assistant_message")]
    pub last_assistant_message: Option<String>,
    #[serde(rename = "message")]
    pub message: Option<String>,
    #[serde(rename = "model")]
    pub model: Option<String>,
    #[serde(rename = "model_request_id")]
    pub model_request_id: Option<String>,
    #[serde(rename = "needs_follow_up")]
    pub needs_follow_up: Option<bool>,
    #[serde(rename = "notification_type")]
    pub notification_type: Option<String>,
    #[serde(rename = "output_bytes")]
    pub output_bytes: Option<u64>,
    #[serde(rename = "output_preview")]
    pub output_preview: Option<String>,
    #[serde(rename = "parallel_tool_calls")]
    pub parallel_tool_calls: Option<bool>,
    #[serde(rename = "paths")]
    pub paths: Option<Vec<String>>,
    #[serde(rename = "permission_mode")]
    pub permission_mode: String,
    #[serde(rename = "prompt")]
    pub prompt: Option<String>,
    #[serde(rename = "proposed_execpolicy_amendment")]
    pub proposed_execpolicy_amendment: Option<Vec<String>>,
    #[serde(rename = "provider")]
    pub provider: Option<String>,
    #[serde(rename = "reason")]
    pub reason: Option<String>,
    #[serde(rename = "request_id")]
    pub request_id: Option<String>,
    #[serde(rename = "response_id")]
    pub response_id: Option<String>,
    #[serde(rename = "sandbox_policy")]
    pub sandbox_policy: Option<Value>,
    #[serde(rename = "schema_version")]
    pub schema_version: u64,
    #[serde(rename = "server_name")]
    pub server_name: Option<String>,
    #[serde(rename = "session_id")]
    pub session_id: String,
    #[serde(rename = "session_source")]
    pub session_source: Option<String>,
    #[serde(rename = "status")]
    pub status: Option<String>,
    #[serde(rename = "subagent")]
    pub subagent: Option<String>,
    #[serde(rename = "success")]
    pub success: Option<bool>,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "title")]
    pub title: Option<String>,
    #[serde(rename = "token_usage")]
    pub token_usage: Option<Value>,
    #[serde(rename = "tool_count")]
    pub tool_count: Option<u64>,
    #[serde(rename = "tool_input")]
    pub tool_input: Option<Value>,
    #[serde(rename = "tool_name")]
    pub tool_name: Option<String>,
    #[serde(rename = "tool_response")]
    pub tool_response: Option<Value>,
    #[serde(rename = "tool_use_id")]
    pub tool_use_id: Option<String>,
    #[serde(rename = "transcript_path")]
    pub transcript_path: String,
    #[serde(rename = "trigger")]
    pub trigger: Option<String>,
    #[serde(rename = "turn_id")]
    pub turn_id: Option<String>,
    #[serde(rename = "xcodex_event_type")]
    pub xcodex_event_type: String,
    #[serde(flatten)]
    pub extra: ExtraFields,
}
