// Code generated by `codex-core/src/bin/hooks_go_types.rs`. DO NOT EDIT.
//
// xCodex hooks kit: Go typed helpers for external hooks.
//
// This file is installed under `$CODEX_HOME/hooks/templates/go/` by:
//   xcodex hooks install sdks go
//
// Re-generate from the repo:
//   cd codex-rs
//   cargo run -p codex-core --bin hooks_go_types --features hooks-schema --quiet \
//     > common/src/hooks_sdk_assets/go/hooksdk/types.go
package hooksdk

import (
	"encoding/json"
)

// HookPayload models the JSON payload shape emitted by xcodex hooks.
// Unknown fields are preserved in RawPayload for forward compatibility.
type HookPayload struct {
	RawPayload map[string]any `json:"-"`
	ApprovalId *string `json:"approval_id"`
	ApprovalPolicy any `json:"approval_policy"`
	Attempt *int `json:"attempt"`
	CallId *string `json:"call_id"`
	Command []string `json:"command"`
	Cwd string `json:"cwd"`
	DurationMs *int `json:"duration_ms"`
	EventId string `json:"event_id"`
	GrantRoot *string `json:"grant_root"`
	HasOutputSchema *bool `json:"has_output_schema"`
	HookEventName string `json:"hook_event_name"`
	InputItemCount *int `json:"input_item_count"`
	InputMessages []string `json:"input_messages"`
	Kind *string `json:"kind"`
	LastAssistantMessage *string `json:"last_assistant_message"`
	Message *string `json:"message"`
	Model *string `json:"model"`
	ModelRequestId *string `json:"model_request_id"`
	NeedsFollowUp *bool `json:"needs_follow_up"`
	NotificationType *string `json:"notification_type"`
	OutputBytes *int `json:"output_bytes"`
	OutputPreview *string `json:"output_preview"`
	ParallelToolCalls *bool `json:"parallel_tool_calls"`
	Paths []string `json:"paths"`
	PermissionMode string `json:"permission_mode"`
	Prompt *string `json:"prompt"`
	ProposedExecpolicyAmendment []string `json:"proposed_execpolicy_amendment"`
	Provider *string `json:"provider"`
	Reason *string `json:"reason"`
	RequestId *string `json:"request_id"`
	ResponseId *string `json:"response_id"`
	SandboxPolicy any `json:"sandbox_policy"`
	SchemaVersion int `json:"schema_version"`
	ServerName *string `json:"server_name"`
	SessionId string `json:"session_id"`
	SessionSource *string `json:"session_source"`
	Status *string `json:"status"`
	Subagent *string `json:"subagent"`
	Success *bool `json:"success"`
	Timestamp string `json:"timestamp"`
	Title *string `json:"title"`
	TokenUsage any `json:"token_usage"`
	ToolCount *int `json:"tool_count"`
	ToolInput any `json:"tool_input"`
	ToolName *string `json:"tool_name"`
	ToolResponse any `json:"tool_response"`
	ToolUseId *string `json:"tool_use_id"`
	TranscriptPath string `json:"transcript_path"`
	Trigger *string `json:"trigger"`
	TurnId *string `json:"turn_id"`
	XcodexEventType string `json:"xcodex_event_type"`
}

func (p *HookPayload) UnmarshalJSON(data []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	type Alias HookPayload
	var a Alias
	if err := json.Unmarshal(data, &a); err != nil {
		return err
	}

	*p = HookPayload(a)
	p.RawPayload = raw
	return nil
}

// ParseHookPayload parses a hook JSON payload into a HookPayload.
func ParseHookPayload(data []byte) (*HookPayload, error) {
	var p HookPayload
	if err := json.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return &p, nil
}
